name: base-package
on:
  workflow_call:
    inputs:
      path:
        description: 'package dirs'
        type: string
        required: true
      file:
        description: 'package output file'
        type: string
        required: true

jobs:
  base-package:
    name: ${{inputs.file}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: |
          cd ${{ inputs.path }}
          tar -cvzf ${{ inputs.file }} *
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.file }}
          path: ${{ inputs.path }}/${{ inputs.file }}
      # too old
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ inputs.path }}/${{ inputs.file }}